### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/thingy#1]
Milestone for Mint 20.3
------------------------------

- [x] Add translations to Launchpad
- [x] Remove landing page in xreader
- [x] Add icon in mint-y
- [x] Add icon in mint-x
- [x] Remember window size, position and state

Ideas for Mint 21
----------------------

- [ ] Add support for other content types (movies, pictures, office documents..)
- [ ] Add filtering by type
- [x] Add the ability to add/remove favorites
- [ ] Add the ability to create collections

**Comment by hugok79** [comment]
The translations are already in Launchpad https://translations.launchpad.net/linuxmint/latest/+pots/thingy/
Portuguese translations are done

**Comment by m-dorokhin** [comment]
Do you planned add scanning of all disks and creation document library. It will be very useful feature and I will be very grateful to you!

**Comment by shenlebantongying** [comment]
I just tried the software, and it is really nice. My major problem with it is that it doesn't support readers like Okular/Evince............

**Comment by bulmust** [comment]
Making group of documents or folder structure may be useful.

**Comment by haggen88** [comment]
I agree, being able to make a group of documents would be very useful. Btw maybe you could also add a symbolic icon [something like this: [thingy-symbolic.svg.zip](https://github.com/linuxmint/thingy/files/11637393/thingy-symbolic.svg.zip)]
